apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lalavisit

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: lalavisit
  app.kubernetes.io/managed-by: kustomize
